In [116]:
import pandas as pd
import numpy as np

In [117]:
df_orig = pd.read_excel('data/test.xlsx')
df_orig.head()

,Resource Name,Project/SSCR name,Planned Release month,Project Role,Legato Manager Name,Anthem Manager,Project Model,Planned Hours,Actual Hours,Remaining Hours,...,Actual Task7 Hours,Task7Comments,Actual Task8 Hours,Task8Comments,Actual Task9 Hours,Task9Comments,Actual Task10 Hours,Task10Comments,Actual Away From Work Hours,AwayFromWorkComments
0,"Gangwar, Kamal [AF40660]",Cotiviti Online & Adjustments Phase 1- Sep,September 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,96.0,125.0,-29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Gangwar, Kamal [AF40660]",Others,NaN,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,Sick Leave - [8.00];Holiday - [8.00]
2,"Gangwar, Kamal [AF40660]",PV36064 Cotiviti Pre to Post Phase 3,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,52.0,7.5,44.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Gangwar, Kamal [AF40660]",PV36064_Cotiviti expansion,February 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Gangwar, Kamal [AF40660]",PV38761 ClaimXten Expansion,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,36.0,0.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
df_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 83 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Resource Name                                     42 non-null     object
 1   Project/SSCR name                                 42 non-null     object
 2   Planned Release month                             36 non-null     object
 3   Project Role                                      42 non-null     object
 4   Legato Manager Name                               42 non-null     object
 5   Anthem Manager                                    42 non-null     object
 6   Project Model                                     36 non-null     object
 7   Planned Hours                                     36 non-null     float64
 8   Actual Hours                                      36 non-null     float64
 9   Remaining Hours                                   36 non-null     float64
 10  Planned Requirements Hours                        32 non-null     float64
 11  Planned Requirement Analysis Hours                32 non-null     float64
 12  Actual BRD Hours                                  0 non-null      float64
 13  Actual BRD Review Hours                           0 non-null      float64
 14  Planned Design Hours                              32 non-null     float64
 15  Planned Test Design Hours                         32 non-null     float64
 16  Actual LOE 90% Hours                              0 non-null      float64
 17  Actual TDD Hours                                  3 non-null      float64
 18  Actual Unit Test Plan Hours                       1 non-null      float64
 19  Actual Design Review Hours                        3 non-null      float64
 20  Planned Development Hours                         32 non-null     float64
 21  Planned Test Data Creation Hours                  32 non-null     float64
 22  Actual Coding Hours                               14 non-null     float64
 23  Actual Unit Testing Hours                         14 non-null     float64
 24  Actual Code UT Review Hours                       8 non-null      float64
 25  Actual Code Retro Fit Hours                       4 non-null      float64
 26  Actual SIT Test Plan Hours                        3 non-null      float64
 27  Actual SIT Preparation Review Hours               4 non-null      float64
 28  Planned SIT Hours                                 32 non-null     float64
 29  Planned Test Execution Hours                      32 non-null     float64
 30  Actual Test Execution Hours                       0 non-null      float64
 31  Actual Test Review Hours                          1 non-null      float64
 32  Actual Requirement Analysis                       0 non-null      float64
 33  Actual Test Design                                0 non-null      float64
 34  Actual Test Data Creation                         0 non-null      float64
 35  Actual Defect Management                          0 non-null      float64
 36  Actual Communication And Status Reporting         0 non-null      float64
 37  Actual Rework                                     0 non-null      float64
 38  Planned UAT Hours                                 32 non-null     float64
 39  Test Review Hours                                 32 non-null     float64
 40  Actual UAT Code Retro Fit Hours                   0 non-null      float64
 41  Actual UAT Code Fix Hours                         0 non-null      float64
 42  Actual UAT Fix Test Hours                         0 non-null      float64
 43  Planned STC Hours                                 32 non-null     float64
 44  Defect Management Hours                           32 non-null     float64
 45  Actual STC Results Review Hours                   2 non-null      float64
 46  Actual STC Code Fix Hours                         1 non-null      float64
 47  Actual STC Fix Test Hours                         1 non-null      float64
 48  Planned Release Hours                             32 non-null     float64
 49  Planned Communication and Status Reporting Hours  32 non-null     float64
 50  Actual Release Checklist Hours                    3 non-null      float64
 51  Actual Implementation Support Hours               1 non-null      float64
 52  Actual Post Implementation Support Hours          2 non-null      float64
 53  Planned Warranty Support Hours                    32 non-null     float64
 54  Planned Rework Hours                              32 non-null     float64
 55  Actual Warranty Hours                             0 non-null      float64
 56  Actual Adhoc Hours                                0 non-null      float64
 57  Actual Adhoc Analysis Hours                       14 non-null     float64
 58  Actual Idle Time Hours                            0 non-null      float64
 59  Actual PTO Hours                                  0 non-null      float64
 60  Actual Total Other Hours                          6 non-null      float64
 61  Actual Task1 Hours                                1 non-null      float64
 62  Task1Comments                                     1 non-null      object
 63  Actual Task2 Hours                                1 non-null      float64
 64  Task2Comments                                     1 non-null      object
 65  Actual Task3 Hours                                1 non-null      float64
 66  Task3Comments                                     1 non-null      object
 67  Actual Task4 Hours                                0 non-null      float64
 68  Task4Comments                                     0 non-null      float64
 69  Actual Task5 Hours                                0 non-null      float64
 70  Task5Comments                                     0 non-null      float64
 71  Actual Task6 Hours                                0 non-null      float64
 72  Task6Comments                                     0 non-null      float64
 73  Actual Task7 Hours                                0 non-null      float64
 74  Task7Comments                                     0 non-null      float64
 75  Actual Task8 Hours                                0 non-null      float64
 76  Task8Comments                                     0 non-null      float64
 77  Actual Task9 Hours                                0 non-null      float64
 78  Task9Comments                                     0 non-null      float64
 79  Actual Task10 Hours                               0 non-null      float64
 80  Task10Comments                                    0 non-null      float64
 81  Actual Away From Work Hours                       6 non-null      float64
 82  AwayFromWorkComments                              6 non-null      object
dtypes: float64(72), object(11)
memory usage: 27.4+ KB

In [119]:
df_copy = df_orig.copy()

In [120]:
print(id(df_orig))
print(id(df_copy))

2500840821576
2500840731720

In [121]:
pd.reset_option('display.max_rows')

In [122]:
comments_col_index_array = np.arange(62,84,2)
comments_col_index_array

array([62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82])

In [123]:
#df_copy.columns[comments_col_index_array]
df_copy.drop(df_copy.columns[comments_col_index_array],axis=1,inplace=True)

In [124]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 72 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Resource Name                                     42 non-null     object
 1   Project/SSCR name                                 42 non-null     object
 2   Planned Release month                             36 non-null     object
 3   Project Role                                      42 non-null     object
 4   Legato Manager Name                               42 non-null     object
 5   Anthem Manager                                    42 non-null     object
 6   Project Model                                     36 non-null     object
 7   Planned Hours                                     36 non-null     float64
 8   Actual Hours                                      36 non-null     float64
 9   Remaining Hours                                   36 non-null     float64
 10  Planned Requirements Hours                        32 non-null     float64
 11  Planned Requirement Analysis Hours                32 non-null     float64
 12  Actual BRD Hours                                  0 non-null      float64
 13  Actual BRD Review Hours                           0 non-null      float64
 14  Planned Design Hours                              32 non-null     float64
 15  Planned Test Design Hours                         32 non-null     float64
 16  Actual LOE 90% Hours                              0 non-null      float64
 17  Actual TDD Hours                                  3 non-null      float64
 18  Actual Unit Test Plan Hours                       1 non-null      float64
 19  Actual Design Review Hours                        3 non-null      float64
 20  Planned Development Hours                         32 non-null     float64
 21  Planned Test Data Creation Hours                  32 non-null     float64
 22  Actual Coding Hours                               14 non-null     float64
 23  Actual Unit Testing Hours                         14 non-null     float64
 24  Actual Code UT Review Hours                       8 non-null      float64
 25  Actual Code Retro Fit Hours                       4 non-null      float64
 26  Actual SIT Test Plan Hours                        3 non-null      float64
 27  Actual SIT Preparation Review Hours               4 non-null      float64
 28  Planned SIT Hours                                 32 non-null     float64
 29  Planned Test Execution Hours                      32 non-null     float64
 30  Actual Test Execution Hours                       0 non-null      float64
 31  Actual Test Review Hours                          1 non-null      float64
 32  Actual Requirement Analysis                       0 non-null      float64
 33  Actual Test Design                                0 non-null      float64
 34  Actual Test Data Creation                         0 non-null      float64
 35  Actual Defect Management                          0 non-null      float64
 36  Actual Communication And Status Reporting         0 non-null      float64
 37  Actual Rework                                     0 non-null      float64
 38  Planned UAT Hours                                 32 non-null     float64
 39  Test Review Hours                                 32 non-null     float64
 40  Actual UAT Code Retro Fit Hours                   0 non-null      float64
 41  Actual UAT Code Fix Hours                         0 non-null      float64
 42  Actual UAT Fix Test Hours                         0 non-null      float64
 43  Planned STC Hours                                 32 non-null     float64
 44  Defect Management Hours                           32 non-null     float64
 45  Actual STC Results Review Hours                   2 non-null      float64
 46  Actual STC Code Fix Hours                         1 non-null      float64
 47  Actual STC Fix Test Hours                         1 non-null      float64
 48  Planned Release Hours                             32 non-null     float64
 49  Planned Communication and Status Reporting Hours  32 non-null     float64
 50  Actual Release Checklist Hours                    3 non-null      float64
 51  Actual Implementation Support Hours               1 non-null      float64
 52  Actual Post Implementation Support Hours          2 non-null      float64
 53  Planned Warranty Support Hours                    32 non-null     float64
 54  Planned Rework Hours                              32 non-null     float64
 55  Actual Warranty Hours                             0 non-null      float64
 56  Actual Adhoc Hours                                0 non-null      float64
 57  Actual Adhoc Analysis Hours                       14 non-null     float64
 58  Actual Idle Time Hours                            0 non-null      float64
 59  Actual PTO Hours                                  0 non-null      float64
 60  Actual Total Other Hours                          6 non-null      float64
 61  Actual Task1 Hours                                1 non-null      float64
 62  Actual Task2 Hours                                1 non-null      float64
 63  Actual Task3 Hours                                1 non-null      float64
 64  Actual Task4 Hours                                0 non-null      float64
 65  Actual Task5 Hours                                0 non-null      float64
 66  Actual Task6 Hours                                0 non-null      float64
 67  Actual Task7 Hours                                0 non-null      float64
 68  Actual Task8 Hours                                0 non-null      float64
 69  Actual Task9 Hours                                0 non-null      float64
 70  Actual Task10 Hours                               0 non-null      float64
 71  Actual Away From Work Hours                       6 non-null      float64
dtypes: float64(65), object(7)
memory usage: 23.8+ KB

In [125]:
Idvars = df_copy.columns.values[:10]
Valuevars = df_copy.columns.values[10:] 

df_melt = pd.melt(df_copy,
                  id_vars = Idvars,
                  value_vars = Valuevars,
                  value_name = 'Hours'
                 )
df_melt.head()

,Resource Name,Project/SSCR name,Planned Release month,Project Role,Legato Manager Name,Anthem Manager,Project Model,Planned Hours,Actual Hours,Remaining Hours,variable,Hours
0,"Gangwar, Kamal [AF40660]",Cotiviti Online & Adjustments Phase 1- Sep,September 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,96.0,125.0,-29.0,Planned Requirements Hours,400.0
1,"Gangwar, Kamal [AF40660]",Others,NaN,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,NaN,NaN,NaN,NaN,Planned Requirements Hours,NaN
2,"Gangwar, Kamal [AF40660]",PV36064 Cotiviti Pre to Post Phase 3,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,52.0,7.5,44.5,Planned Requirements Hours,0.0
3,"Gangwar, Kamal [AF40660]",PV36064_Cotiviti expansion,February 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,0.0,0.0,0.0,Planned Requirements Hours,NaN
4,"Gangwar, Kamal [AF40660]",PV38761 ClaimXten Expansion,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,36.0,0.0,36.0,Planned Requirements Hours,200.0

In [126]:
colsplit = df_melt['variable'].str.split(' ', 1)
df_melt['Effort Type'] = colsplit.str[0]
df_melt['Task Name'] = colsplit.str[1]
df_melt.head()

,Resource Name,Project/SSCR name,Planned Release month,Project Role,Legato Manager Name,Anthem Manager,Project Model,Planned Hours,Actual Hours,Remaining Hours,variable,Hours,Effort Type,Task Name
0,"Gangwar, Kamal [AF40660]",Cotiviti Online & Adjustments Phase 1- Sep,September 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,96.0,125.0,-29.0,Planned Requirements Hours,400.0,Planned,Requirements Hours
1,"Gangwar, Kamal [AF40660]",Others,NaN,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,NaN,NaN,NaN,NaN,Planned Requirements Hours,NaN,Planned,Requirements Hours
2,"Gangwar, Kamal [AF40660]",PV36064 Cotiviti Pre to Post Phase 3,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,52.0,7.5,44.5,Planned Requirements Hours,0.0,Planned,Requirements Hours
3,"Gangwar, Kamal [AF40660]",PV36064_Cotiviti expansion,February 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,0.0,0.0,0.0,Planned Requirements Hours,NaN,Planned,Requirements Hours
4,"Gangwar, Kamal [AF40660]",PV38761 ClaimXten Expansion,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,36.0,0.0,36.0,Planned Requirements Hours,200.0,Planned,Requirements Hours

In [127]:
#df_melt['Task Name'] = df_melt['Task Name'].str.split(' ', -1)'
#df_melt['Task Name'].str.rsplit(' ', 1)
df_melt['Task Name']= df_melt['Task Name'].str.rstrip('Hours')

In [128]:
df_melt.drop('variable', axis=1, inplace=True)

In [129]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2604 entries, 0 to 2603
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Resource Name          2604 non-null   object
 1   Project/SSCR name      2604 non-null   object
 2   Planned Release month  2232 non-null   object
 3   Project Role           2604 non-null   object
 4   Legato Manager Name    2604 non-null   object
 5   Anthem Manager         2604 non-null   object
 6   Project Model          2232 non-null   object
 7   Planned Hours          2232 non-null   float64
 8   Actual Hours           2232 non-null   float64
 9   Remaining Hours        2232 non-null   float64
 10  Hours                  606 non-null    float64
 11  Effort Type            2604 non-null   object
 12  Task Name              2604 non-null   object
dtypes: float64(4), object(9)
memory usage: 264.6+ KB

In [130]:
df_melt.rename(columns={'Planned Hours':'Total Planned Hours',
                        'Actual Hours':'Total Actual Hours',
                        'Remaining Hours':'Total Remaining Hours'},
               inplace=True)
df_melt['AGID'] = df_melt['Resource Name'].str[-8:-1]

In [131]:
df_melt['Resource Name'] = df_melt['Resource Name'].str[:-9]
df_melt

,Resource Name,Project/SSCR name,Planned Release month,Project Role,Legato Manager Name,Anthem Manager,Project Model,Total Planned Hours,Total Actual Hours,Total Remaining Hours,Hours,Effort Type,Task Name,AGID
0,"Gangwar, Kamal",Cotiviti Online & Adjustments Phase 1- Sep,September 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,96.0,125.0,-29.0,400.0,Planned,Requirements,AF40660
1,"Gangwar, Kamal",Others,NaN,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,NaN,NaN,NaN,NaN,NaN,Planned,Requirements,AF40660
2,"Gangwar, Kamal",PV36064 Cotiviti Pre to Post Phase 3,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,52.0,7.5,44.5,0.0,Planned,Requirements,AF40660
3,"Gangwar, Kamal",PV36064_Cotiviti expansion,February 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,0.0,0.0,0.0,NaN,Planned,Requirements,AF40660
4,"Gangwar, Kamal",PV38761 ClaimXten Expansion,June 2020,Senior Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,36.0,0.0,36.0,200.0,Planned,Requirements,AF40660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599,"Pradhan, Jyotirekha",PV36064_Cotiviti expansion,February 2020,Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,0.0,0.0,0.0,NaN,Actual,Away From Work,AG18454
2600,"Reddy, Madhan",Cotiviti Expansion July Release,July 2020,Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,100.0,80.7,19.3,NaN,Actual,Away From Work,AG61751
2601,"Reddy, Madhan",Cotiviti Online & Adjustments Phase 1- Sep,September 2020,Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,64.0,96.5,-32.5,NaN,Actual,Away From Work,AG61751
2602,"Reddy, Madhan",Others,NaN,Software Engineer,"Ghosh, Ayan",Saxon Joseph,NaN,NaN,NaN,NaN,8.0,Actual,Away From Work,AG61751
2603,"Reddy, Madhan",PV38761 ClaimXten Expansion,June 2020,Software Engineer,"Ghosh, Ayan",Saxon Joseph,Waterfall,20.0,0.0,20.0,NaN,Actual,Away From Work,AG61751

In [132]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2604 entries, 0 to 2603
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Resource Name          2604 non-null   object
 1   Project/SSCR name      2604 non-null   object
 2   Planned Release month  2232 non-null   object
 3   Project Role           2604 non-null   object
 4   Legato Manager Name    2604 non-null   object
 5   Anthem Manager         2604 non-null   object
 6   Project Model          2232 non-null   object
 7   Total Planned Hours    2232 non-null   float64
 8   Total Actual Hours     2232 non-null   float64
 9   Total Remaining Hours  2232 non-null   float64
 10  Hours                  606 non-null    float64
 11  Effort Type            2604 non-null   object
 12  Task Name              2604 non-null   object
 13  AGID                   2604 non-null   object
dtypes: float64(4), object(10)
memory usage: 284.9+ KB

In [133]:
x = df_melt.columns.values
y = [x[0], x[13], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9], x[11], x[12], x[10]]
df_melt = df_melt.reindex(y, axis=1)

In [134]:
#df_melt
df_melt.to_excel('data/melt.xlsx', index = False)